# Generated by Django 5.2.1 on 2025-06-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Por Hacer', 'Por Hacer'), ('En Progreso', 'En Progreso'), ('Hecha', 'Hecha')], default='Por Hacer', max_length=20)),
                ('archivos', models.FileField(blank=True, null=True, upload_to='tareas_archivo/')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.usuarioproyecto')),
                ('historia_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.historiausuario')),
            ],
        ),
    ]
