# Generated by Django 5.2.1 on 2025-07-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.historiausuario'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='invitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.invitacion'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.tarea'),
        ),
    ]
